In [109]:
import pandas as pd 

df = pd.read_csv("orders.csv")

In [43]:
df

,OrderID,CustomerName,Email,Product,Category,Quantity,Price,OrderDate,Shipped,country,ProductName
0,1001,John Smith,john.smith@example.com,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA,NaN
1,1002,Sarah Lee,sarah.lee@example.com,Headphones,Electronics,2,150.0,2024-06-03,No,Canada,NaN
2,1003,Ali Khan,ali.khan@example.com,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE,NaN
3,1004,Alice Wong,alice.wong@example.com,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore,NaN
4,1005,Carlos Mendez,carlos.mendez@example.com,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico,NaN
5,1006,Nora Ibrahim,nora.ibrahim@example.com,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE,NaN
6,1007,Emily Davis,emily.davis@example.com,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK,NaN
7,1008,James Park,james.park@example.com,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea,NaN
8,1009,Maria Rossi,maria.rossi@example.com,Pen,Stationery,10,1.5,2024-06-10,Yes,Italy,NaN
9,1010,Takeshi Nakamura,takeshi.nakamura@example.com,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan,NaN
10,1011,Sophie Martin,sophie.martin@example.com,Webcam,Electronics,1,85.0,2024-06-12,Yes,France,NaN
11,1012,Raj Patel,raj.patel@example.com,File Cabinet,Furniture,2,180.0,2024-06-13,No,India,NaN
12,1013,Emma Wilson,emma.wilson@example.com,Stapler,Stationery,3,12.0,2024-06-14,Yes,Australia,NaN
13,1014,Diego Rodriguez,diego.rodriguez@example.com,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain,NaN
14,1015,Lisa Chen,lisa.chen@example.com,Bookshelf,Furniture,1,280.0,2024-06-16,No,China,NaN
15,1016,Ahmed Hassan,ahmed.hassan@example.com,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt,NaN
16,1017,Anna Kowalski,anna.kowalski@example.com,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland,NaN
17,1018,Michael Brown,michael.brown@example.com,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA,NaN
18,1019,Yuki Tanaka,yuki.tanaka@example.com,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan,NaN
19,1020,Fatima Al-Zahra,fatima.alzahra@example.com,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,Saudi Arabia,NaN
20,1021,David Thompson,david.thompson@example.com,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada,NaN
21,1022,Isabella Silva,isabella.silva@example.com,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil,NaN
22,1023,Oliver Schmidt,oliver.schmidt@example.com,Office Plant,Furniture,2,35.0,2024-06-24,Yes,Germany,NaN
23,1024,Zara Ahmed,zara.ahmed@example.com,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan,NaN
24,1025,Lucas Anderson,lucas.anderson@example.com,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden,NaN
25,1026,Chloe Dubois,chloe.dubois@example.com,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France,NaN
26,1027,Miguel Torres,miguel.torres@example.com,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,Argentina,NaN
27,1028,Nina Petrov,nina.petrov@example.com,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,Russia,NaN
28,1029,Seo-yeon Kim,seoyeon.kim@example.com,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea,NaN
29,1030,Giuseppe Romano,giuseppe.romano@example.com,Desk Calendar,Furniture,1,18.0,2024-07-01,No,Italy,NaN
30,1031,Amira Hassan,amira.hassan@example.com,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco,NaN
31,1032,Thomas Müller,thomas.muller@example.com,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany,NaN
32,1033,Sofia Rodriguez,sofia.rodriguez@example.com,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,Colombia,NaN
33,1034,Alex Johnson,alex.johnson@example.com,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA,NaN
34,1035,Yuki Yamamoto,yuki.yamamoto@example.com,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan,NaN
35,1036,Emma Thompson,emma.thompson@example.com,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK,NaN
36,1037,Carlos Santos,carlos.santos@example.com,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal,NaN
37,1038,Leila Mansouri,leila.mansouri@example.com,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran,NaN
38,1039,Daniel Kim,daniel.kim@example.com,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea,NaN
39,1040,Anna Ivanova,anna.ivanova@example.com,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine,New Product Name

In [11]:
df.head()

,OrderID,CustomerName,Email,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,john.smith@example.com,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,sarah.lee@example.com,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,ali.khan@example.com,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,alice.wong@example.com,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,carlos.mendez@example.com,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico

In [14]:
df.tail()

,OrderID,CustomerName,Email,Product,Category,Quantity,Price,OrderDate,Shipped,Country
35,1036,Emma Thompson,emma.thompson@example.com,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,carlos.santos@example.com,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Leila Mansouri,leila.mansouri@example.com,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
38,1039,Daniel Kim,daniel.kim@example.com,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea
39,1040,Anna Ivanova,anna.ivanova@example.com,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [ ]:
df["country"]

0              USA
1           Canada
2              UAE
3        Singapore
4           Mexico
5              UAE
6               UK
7      South Korea
8            Italy
9            Japan
10          France
11           India
12       Australia
13           Spain
14           China
15           Egypt
16          Poland
17             USA
18           Japan
19    Saudi Arabia
20          Canada
21          Brazil
22         Germany
23        Pakistan
24          Sweden
25          France
26       Argentina
27          Russia
28     South Korea
29           Italy
30         Morocco
31         Germany
32        Colombia
33             USA
34           Japan
35              UK
36        Portugal
37            Iran
38     South Korea
39         Ukraine
Name: country, dtype: str

In [75]:
df.iloc[10]['Product']

'Laptop'

In [ ]:
df.loc[df['Email'] == 'sophie.martin@example.com', 'Product'] = 'Laptop'

In [62]:
df[(df['Category'] == 'Furniture') & (df['country'] == 'UK')]

,OrderID,CustomerName,Email,Product,Category,Quantity,Price,OrderDate,Shipped,country,ProductName
6,1007,Emily Davis,emily.davis@example.com,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK,NaN
35,1036,Emma Thompson,emma.thompson@example.com,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK,NaN

In [28]:
df[df['Quantity'] > 50]

,OrderID,CustomerName,Email,Product,Category,Quantity,Price,OrderDate,Shipped,Country
33,1034,Alex Johnson,alex.johnson@example.com,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA

In [63]:
df[df["CustomerName"].str.startswith("Thomas")]

,OrderID,CustomerName,Email,Product,Category,Quantity,Price,OrderDate,Shipped,country,ProductName
31,1032,Thomas Müller,thomas.muller@example.com,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany,NaN

In [66]:
df[df["country"].isin(["USA", "Canada"])]
#tilde before second df to reverse the filter

,OrderID,CustomerName,Email,Product,Category,Quantity,Price,OrderDate,Shipped,country,ProductName
0,1001,John Smith,john.smith@example.com,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA,NaN
1,1002,Sarah Lee,sarah.lee@example.com,Headphones,Electronics,2,150.0,2024-06-03,No,Canada,NaN
17,1018,Michael Brown,michael.brown@example.com,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA,NaN
20,1021,David Thompson,david.thompson@example.com,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada,NaN
33,1034,Alex Johnson,alex.johnson@example.com,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA,NaN

In [67]:
df.loc[df['CustomerName'] == 'Anna Ivanova', 'ProductName'] = 'New Product Name'

In [83]:
(df[df['CustomerName'] == 'Anna Ivanova'])

,OrderID,CustomerName,Email,Product,Category,Quantity,Price,OrderDate,Shipped,country,ProductName
39,1040,Anna Ivanova,anna.ivanova@example.com,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine,New Product Name

In [ ]:
df['Country'] = df['country'].str.upper()

,OrderID,CustomerName,Email,Product,Category,Quantity,Price,OrderDate,Shipped,country,ProductName,Country
0,1001,John Smith,john.smith@example.com,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA,NaN,USA
1,1002,Sarah Lee,sarah.lee@example.com,Headphones,Electronics,2,150.0,2024-06-03,No,Canada,NaN,CANADA
2,1003,Ali Khan,ali.khan@example.com,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE,NaN,UAE
3,1004,Alice Wong,alice.wong@example.com,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore,NaN,SINGAPORE
4,1005,Carlos Mendez,carlos.mendez@example.com,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico,NaN,MEXICO
5,1006,Nora Ibrahim,nora.ibrahim@example.com,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE,NaN,UAE
6,1007,Emily Davis,emily.davis@example.com,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK,NaN,UK
7,1008,James Park,james.park@example.com,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea,NaN,SOUTH KOREA
8,1009,Maria Rossi,maria.rossi@example.com,Pen,Stationery,10,1.5,2024-06-10,Yes,Italy,NaN,ITALY
9,1010,Takeshi Nakamura,takeshi.nakamura@example.com,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan,NaN,JAPAN
10,1011,Sophie Martin,sophie.martin@example.com,Laptop,Electronics,1,85.0,2024-06-12,Yes,France,NaN,FRANCE
11,1012,Raj Patel,raj.patel@example.com,File Cabinet,Furniture,2,180.0,2024-06-13,No,India,NaN,INDIA
12,1013,Emma Wilson,emma.wilson@example.com,Stapler,Stationery,3,12.0,2024-06-14,Yes,Australia,NaN,AUSTRALIA
13,1014,Diego Rodriguez,diego.rodriguez@example.com,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain,NaN,SPAIN
14,1015,Lisa Chen,lisa.chen@example.com,Bookshelf,Furniture,1,280.0,2024-06-16,No,China,NaN,CHINA
15,1016,Ahmed Hassan,ahmed.hassan@example.com,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt,NaN,EGYPT
16,1017,Anna Kowalski,anna.kowalski@example.com,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland,NaN,POLAND
17,1018,Michael Brown,michael.brown@example.com,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA,NaN,USA
18,1019,Yuki Tanaka,yuki.tanaka@example.com,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan,NaN,JAPAN
19,1020,Fatima Al-Zahra,fatima.alzahra@example.com,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,Saudi Arabia,NaN,SAUDI ARABIA
20,1021,David Thompson,david.thompson@example.com,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada,NaN,CANADA
21,1022,Isabella Silva,isabella.silva@example.com,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil,NaN,BRAZIL
22,1023,Oliver Schmidt,oliver.schmidt@example.com,Office Plant,Furniture,2,35.0,2024-06-24,Yes,Germany,NaN,GERMANY
23,1024,Zara Ahmed,zara.ahmed@example.com,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan,NaN,PAKISTAN
24,1025,Lucas Anderson,lucas.anderson@example.com,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden,NaN,SWEDEN
25,1026,Chloe Dubois,chloe.dubois@example.com,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France,NaN,FRANCE
26,1027,Miguel Torres,miguel.torres@example.com,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,Argentina,NaN,ARGENTINA
27,1028,Nina Petrov,nina.petrov@example.com,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,Russia,NaN,RUSSIA
28,1029,Seo-yeon Kim,seoyeon.kim@example.com,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea,NaN,SOUTH KOREA
29,1030,Giuseppe Romano,giuseppe.romano@example.com,Desk Calendar,Furniture,1,18.0,2024-07-01,No,Italy,NaN,ITALY
30,1031,Amira Hassan,amira.hassan@example.com,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco,NaN,MOROCCO
31,1032,Thomas Müller,thomas.muller@example.com,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany,NaN,GERMANY
32,1033,Sofia Rodriguez,sofia.rodriguez@example.com,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,Colombia,NaN,COLOMBIA
33,1034,Alex Johnson,alex.johnson@example.com,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA,NaN,USA
34,1035,Yuki Yamamoto,yuki.yamamoto@example.com,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan,NaN,JAPAN
35,1036,Emma Thompson,emma.thompson@example.com,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK,NaN,UK
36,1037,Carlos Santos,carlos.santos@example.com,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal,NaN,PORTUGAL
37,1038,Leila Mansouri,leila.mansouri@example.com,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran,NaN,IRAN
38,1039,Daniel Kim,daniel.kim@example.com,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea,NaN,SOUTH KOREA
39,1040,Anna Ivanova,anna.ivanova@example.com,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine,New Product Name,UKRAINE

In [ ]:
df

,OrderID,CustomerName,Email,Product,Category,Quantity,Price,OrderDate,Shipped,ProductName
1,1002,Sarah Lee,sarah.lee@example.com,Headphones,Electronics,2,150.0,2024-06-03,No,NaN
2,1003,Ali Khan,ali.khan@example.com,Office Chair,Furniture,1,300.0,2024-06-04,Yes,NaN
3,1004,Alice Wong,alice.wong@example.com,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,NaN
4,1005,Carlos Mendez,carlos.mendez@example.com,Keyboard,Electronics,2,80.0,2024-06-06,No,NaN
5,1006,Nora Ibrahim,nora.ibrahim@example.com,Notebook,Stationery,5,5.0,2024-06-07,Yes,NaN
6,1007,Emily Davis,emily.davis@example.com,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,NaN
7,1008,James Park,james.park@example.com,Monitor,Electronics,2,220.0,2024-06-09,No,NaN
8,1009,Maria Rossi,maria.rossi@example.com,Pen,Stationery,10,1.5,2024-06-10,Yes,NaN
9,1010,Takeshi Nakamura,takeshi.nakamura@example.com,Mouse,Electronics,1,35.0,2024-06-11,Yes,NaN
10,1011,Sophie Martin,sophie.martin@example.com,Laptop,Electronics,1,85.0,2024-06-12,Yes,NaN
11,1012,Raj Patel,raj.patel@example.com,File Cabinet,Furniture,2,180.0,2024-06-13,No,NaN
12,1013,Emma Wilson,emma.wilson@example.com,Stapler,Stationery,3,12.0,2024-06-14,Yes,NaN
13,1014,Diego Rodriguez,diego.rodriguez@example.com,USB Drive,Electronics,5,25.0,2024-06-15,Yes,NaN
14,1015,Lisa Chen,lisa.chen@example.com,Bookshelf,Furniture,1,280.0,2024-06-16,No,NaN
15,1016,Ahmed Hassan,ahmed.hassan@example.com,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,NaN
16,1017,Anna Kowalski,anna.kowalski@example.com,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,NaN
18,1019,Yuki Tanaka,yuki.tanaka@example.com,Calculator,Electronics,1,15.0,2024-06-20,Yes,NaN
19,1020,Fatima Al-Zahra,fatima.alzahra@example.com,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,NaN
20,1021,David Thompson,david.thompson@example.com,Highlighters,Stationery,8,3.5,2024-06-22,No,NaN
21,1022,Isabella Silva,isabella.silva@example.com,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,NaN
22,1023,Oliver Schmidt,oliver.schmidt@example.com,Office Plant,Furniture,2,35.0,2024-06-24,Yes,NaN
23,1024,Zara Ahmed,zara.ahmed@example.com,Sticky Notes,Stationery,15,4.0,2024-06-25,No,NaN
24,1025,Lucas Anderson,lucas.anderson@example.com,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,NaN
25,1026,Chloe Dubois,chloe.dubois@example.com,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,NaN
26,1027,Miguel Torres,miguel.torres@example.com,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,NaN
27,1028,Nina Petrov,nina.petrov@example.com,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,NaN
28,1029,Seo-yeon Kim,seoyeon.kim@example.com,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,NaN
29,1030,Giuseppe Romano,giuseppe.romano@example.com,Desk Calendar,Furniture,1,18.0,2024-07-01,No,NaN
30,1031,Amira Hassan,amira.hassan@example.com,USB Hub,Electronics,1,32.0,2024-07-02,Yes,NaN
31,1032,Thomas Müller,thomas.muller@example.com,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,NaN
32,1033,Sofia Rodriguez,sofia.rodriguez@example.com,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,NaN
34,1035,Yuki Yamamoto,yuki.yamamoto@example.com,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,NaN
35,1036,Emma Thompson,emma.thompson@example.com,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,NaN
36,1037,Carlos Santos,carlos.santos@example.com,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,NaN
37,1038,Leila Mansouri,leila.mansouri@example.com,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,NaN
38,1039,Daniel Kim,daniel.kim@example.com,Power Strip,Electronics,2,18.0,2024-07-10,No,NaN
39,1040,Anna Ivanova,anna.ivanova@example.com,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,New Product Name

In [93]:
df.rename(columns={'Country': 'country'}, inplace=True)

In [111]:
df['Country'].value_counts()

Country
USA             3
South Korea     3
Japan           3
Canada          2
UAE             2
UK              2
Italy           2
France          2
Germany         2
Singapore       1
Mexico          1
India           1
Australia       1
Spain           1
China           1
Egypt           1
Poland          1
Saudi Arabia    1
Brazil          1
Pakistan        1
Sweden          1
Argentina       1
Russia          1
Morocco         1
Colombia        1
Portugal        1
Iran            1
Ukraine         1
Name: count, dtype: int64

In [117]:
df.groupby('Country')['Quantity'].sum()
df.sort_values(by='Quantity', ascending=True)

,OrderID,CustomerName,Email,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,john.smith@example.com,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
2,1003,Ali Khan,ali.khan@example.com,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
6,1007,Emily Davis,emily.davis@example.com,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
9,1010,Takeshi Nakamura,takeshi.nakamura@example.com,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
10,1011,Sophie Martin,sophie.martin@example.com,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
14,1015,Lisa Chen,lisa.chen@example.com,Bookshelf,Furniture,1,280.0,2024-06-16,No,China
29,1030,Giuseppe Romano,giuseppe.romano@example.com,Desk Calendar,Furniture,1,18.0,2024-07-01,No,Italy
30,1031,Amira Hassan,amira.hassan@example.com,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
24,1025,Lucas Anderson,lucas.anderson@example.com,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
25,1026,Chloe Dubois,chloe.dubois@example.com,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
26,1027,Miguel Torres,miguel.torres@example.com,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,Argentina
28,1029,Seo-yeon Kim,seoyeon.kim@example.com,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
21,1022,Isabella Silva,isabella.silva@example.com,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
19,1020,Fatima Al-Zahra,fatima.alzahra@example.com,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,Saudi Arabia
18,1019,Yuki Tanaka,yuki.tanaka@example.com,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
17,1018,Michael Brown,michael.brown@example.com,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
31,1032,Thomas Müller,thomas.muller@example.com,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
35,1036,Emma Thompson,emma.thompson@example.com,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
37,1038,Leila Mansouri,leila.mansouri@example.com,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
39,1040,Anna Ivanova,anna.ivanova@example.com,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine
36,1037,Carlos Santos,carlos.santos@example.com,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
32,1033,Sofia Rodriguez,sofia.rodriguez@example.com,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,Colombia
34,1035,Yuki Yamamoto,yuki.yamamoto@example.com,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan
7,1008,James Park,james.park@example.com,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
22,1023,Oliver Schmidt,oliver.schmidt@example.com,Office Plant,Furniture,2,35.0,2024-06-24,Yes,Germany
38,1039,Daniel Kim,daniel.kim@example.com,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea
1,1002,Sarah Lee,sarah.lee@example.com,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
16,1017,Anna Kowalski,anna.kowalski@example.com,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
11,1012,Raj Patel,raj.patel@example.com,File Cabinet,Furniture,2,180.0,2024-06-13,No,India
4,1005,Carlos Mendez,carlos.mendez@example.com,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
3,1004,Alice Wong,alice.wong@example.com,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
12,1013,Emma Wilson,emma.wilson@example.com,Stapler,Stationery,3,12.0,2024-06-14,Yes,Australia
5,1006,Nora Ibrahim,nora.ibrahim@example.com,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
13,1014,Diego Rodriguez,diego.rodriguez@example.com,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
20,1021,David Thompson,david.thompson@example.com,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
8,1009,Maria Rossi,maria.rossi@example.com,Pen,Stationery,10,1.5,2024-06-10,Yes,Italy
27,1028,Nina Petrov,nina.petrov@example.com,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,Russia
23,1024,Zara Ahmed,zara.ahmed@example.com,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan
15,1016,Ahmed Hassan,ahmed.hassan@example.com,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
33,1034,Alex Johnson,alex.johnson@example.com,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA

In [118]:
# to save 
df.to_csv("updated_orders.csv", index=True)